### ISSUE TITLE
刚才面试的

### ISSUE THREAD

**Issue by zmdgdsx** [BradMoonUESTC/web3jWallet#1]
说了加你微信，发现找不到联系方式

**Comment by BradMoonUESTC** [comment]
XD抱歉好像可能没有留 wx：17695798653



---- 回复的原邮件 ----
| 发件人 | Never ***@***.***> |
| 日期 | 2022年08月31日 18:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [BradMoonUESTC/web3jWallet] 刚才面试的 (Issue #1) |

说了加你微信，发现找不到联系方式
